fix nil pointer bug for container app crawer (#1441)
### Description
Error log:
Azure.ResourceManager.AppContainers.Models.ContainerAppConfiguration.Ingress.get
returned null.
```
fail: Agent.Graph.Services.ResourceGraphCrawlerService[0]
      Internal>>> Error during bulk crawl for /subscriptions/31ce06e2-bf5d-4bdf-9649-243ec548316f/resourcegroups/zhaoziqi-operations-agent-3p-rg/providers/microsoft.app/containerapps/zhaoziqi-aca
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Agent.Graph.Crawler.ARM.ContainerAppCrawler.UpdateContainerAppNode(ContainerAppNode cappNode, ContainerAppData capp) in C:\Users\zhaoziqi\Documents\work\codes\sreagent-runtime\src\Agent\Agent.Graph\Crawler\ARM\ContainerAppCrawler.cs:line 227
         at Agent.Graph.Crawler.ARM.ContainerAppCrawler.Crawl(GraphNode node)+MoveNext() in C:\Users\zhaoziqi\Documents\work\codes\sreagent-runtime\src\Agent\Agent.Graph\Crawler\ARM\ContainerAppCrawler.cs:line 62
         at Agent.Graph.Crawler.ARM.ContainerAppCrawler.Crawl(GraphNode node)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Agent.Graph.Services.ResourceGraphCrawlerService.ExecuteCrawlForNode(GraphNode node, Queue toCrawl, HashSet`1 typeFilters, HashSet`1 scopeFilters, Boolean cascade, Int64 startTS) in C:\Users\zhaoziqi\Documents\work\codes\sreagent-runtime\src\Agent\Agent.Graph\Services\ResourceGraphCrawlerService.cs:line 459
         at Agent.Graph.Services.ResourceGraphCrawlerService.ExecuteCrawlForNode(GraphNode node, Queue toCrawl, HashSet`1 typeFilters, HashSet`1 scopeFilters, Boolean cascade, Int64 startTS) in C:\Users\zhaoziqi\Documents\work\codes\sreagent-runtime\src\Agent\Agent.Graph\Services\ResourceGraphCrawlerService.cs:line 459
         at Agent.Graph.Services.ResourceGraphCrawlerService.<>c__DisplayClass26_1.<<Crawl>b__6>d.MoveNext() in C:\Users\zhaoziqi\Documents\work\codes\sreagent-runtime\src\Agent\Agent.Graph\Services\ResourceGraphCrawlerService.cs:line 365
      --- End of stack trace from previous location ---
         at Agent.Graph.Services.ResourceGraphCrawlerService.ExecuteWithRetry(GraphNode node, Func`2 operation, String operationName) in C:\Users\zhaoziqi\Documents\work\codes\sreagent-runtime\src\Agent\Agent.Graph\Services\ResourceGraphCrawlerService.cs:line 490
```

### Type of Change
<!-- Mark the appropriate option with an 'x', check all that apply -->
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test coverage improvement
- [ ] Prompt change (requires approval from prompt author/owner)

### Risk
<!-- Mark the level of risk associated with this change -->
- [ ] High – Errors could cause MAJOR regression of many scenarios.
(Example: new large features or high-level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios.
(Example: somewhat complex bug fixes, small new features)
- [x] Small – No issues are expected. (Example: Very small bugfixes,
string changes, or configuration settings changes)