fix: ignore other resource provider except aks when creating aks watch crawler (#1744)
### Description
AKS event watch crawler would throw error log when crawl roots are
resource id of a specific resource provider other than subscription,
resource group and AKS cluster, which is able to be set by API.

For instance, when crawl root is an container app
`/subscriptions/31ce06e2-bf5d-4bdf-9649-243ec548316f/resourceGroups/zhaoziqi-operations-agent-3p-rg/providers/Microsoft.App/containerApps/zhaoziqi-aca`

There will be error logs
```
fail: Agent.Graph.Services.KubernetesWatchService[0]
      Internal>>> Failed to list Kubernetes resources for source: Agent.Graph.Services.WatchEventSource
      Azure.RequestFailedException: The Resource 'Microsoft.ContainerService/managedClusters/zhaoziqi-aca' under resource group 'zhaoziqi-operations-agent-3p-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
      Status: 404 (Not Found)
      ErrorCode: ResourceNotFound
```

### Type of Change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test coverage improvement
- [ ] Prompt change (requires approval from prompt author/owner)


### Risk
<!-- Mark the level of risk associated with this change -->
- [ ] High – Errors could cause MAJOR regression of many scenarios.
(Example: new large features or high-level infrastructure changes)
- [ ] Medium – Errors could cause regression of 1 or more scenarios.
(Example: somewhat complex bug fixes, small new features)
- [x] Small – No issues are expected. (Example: Very small bugfixes,
string changes, or configuration settings changes)